apiVersion: v1
kind: Service
metadata:
  name: pegasus-submit-service
  labels:
    app: pegasus-submit-service
spec:
  selector:
    app: pegasus-submit
  type: NodePort
  ports:
  - name: condor
    port: 11000
    targetPort: 11000
    nodePort: $GRIDMANAGER_SERVICE_PORT
    protocol: TCP
